[tool.poetry]
name = "RidenGUI"
version = "0.2.0"
description = "Riden Qt GUI using Qt for Python (PySide2)"
license = "MIT"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
homepage = "https://github.com/ShayBox/RidenGUI"
repository = "https://github.com/ShayBox/RidenGUI.git"

[tool.poetry.dependencies]
PySide2 = "^5.15.2"
python = ">=3.9,<3.10"
riden = {git = "https://github.com/shaybox/riden.git"}

[tool.poetry.dev-dependencies]
black = { version = "^21.11b1", allow-prereleases = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ridengui = "ridengui.main:main"
ridengenui = "ridengui.genui:main"
